config/routes.rb
Rails.application.routes.draw do
  get 'only_page/create_server'
  get 'only_page/install_puppet'
  post 'only_page/run_puppet_script'
  get 'only_page/new_server'
  get 'json_list'=>'only_page#json_list'
  get 'only_page/start_server'
  get 'only_page/stop_server'
  root 'only_page#only_page'

end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/only_page_controller.rb
class OnlyPageController < ApplicationController

  def only_page
    @nesto=Awservice.serverList
  end

  def stop_server
    Awservice.stopServer(params[:server_id])
    render json: 1
  end

  def start_server
    Awservice.startServer(params[:server_id])
    render json: 1
  end

  def new_server
    @images=Image.all
  end

  def create_server
    @server=Awservice.createServer("ami-9dbea4fc")
    render json: @server
  end

  def install_puppet
    Awservice.install_puppet(params[:server_id])
  end


  def run_puppet_script
    Awservice.puppet_script(params[:server_id],params[:what])
    render json: 1
  end

  def json_list
    slist=[]
    Awservice.serverList.each do |s|
      slist<<{id:s.id,state:s.state}
    end
    render json: slist
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/only_page_helper.rb
module OnlyPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ABHAws</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/only_page/new_server.html.erb
<%= form_for :server, url:"#" do |f|%>

<div class="form-group">
<%= f.label :key_name%><br>
<%= f.text_field :key_name, class:"form-control"%>
</div>

<div class="form-group">
  <%= f.label :image_id, "Kategorija"%><br>
    <%=f.select(:image_id,@images.collect{|p|[p.name,p.image_id]},{},{}) %>
</div>
<%end%>

app/views/only_page/only_page.html.erb
<div class="col-md-8 col-md-offset-2  window-border">
  <%= image_tag "abh-aws.jpg",class:"img-responsive" %>
  <h2 class="text-center tbheader" style="font-family: 'Montserrat', sans-serif;">AWS Web GUI</h2>
  <table id="main" class="table console-border">
    <tr>
      <th>
        ID
      </th>
      <th>
        State
      </th>
      <th>
        Key name
      </th>
      <th>
        Options
      </th>
    </tr>
    <% @nesto.each do |s| %>
      <tr id="<%=s.id%>">
        <td>
          <%= s.id %>
        </td>
        <td>
          <%= s.state %>
        </td>
        <td class="keyname">
          <%= s.key_name %>
        </td>
        <td>
          <%= link_to "Stop", only_page_stop_server_path(server_id: s.id),remote:true %> <%= link_to "Start", only_page_start_server_path(server_id: s.id), remote:true %> <%= link_to "Puppet-install", only_page_install_puppet_path(server_id: s.id) %> <a onclick="openConsole('<%=s.id%>')">Configure</a>
        </td>
      </tr>
    <% end %>
    <tr>
      <td>
        Action
      </td>
      <td>

        <a onclick="create()">-> Create <-</a>
      </td>
      <td>

      </td>
      <td>

      </td>
    </tr>
    <tr style="display:none">
      <td>
        Puppet console
      </td>
      <td colspan="3">
        <textarea id="ta_i-b16d5269" name="name" rows="8" cols="40" onkeyup="scriptsend(this)"></textarea>
      </td>
    </tr>

  </table>
  <% if !params[:skript].nil? %>
    <%= Awservice.radi(params[:skript]) %>
  <% end %>
  <div class="collapse" id="collapseExample">
  <div class="well">
    <form class="" action="<%= root_path %>" method="get">
      <textarea name="skript" rows="8" cols="40"></textarea>
      <input type="submit" name="name" value="">
    </form>
  </div>
</div>
</div>

<script>
state=false;
window.setInterval(refresh, 6000);


 function refresh(){
   if(state==false){
     console.log(state);
     state=true;
     console.log(state);
     $.get("/json_list",function(data) {
       for(var i=0;i<data.length;i++){
         child=$("#"+data[i].id).children().eq(1).html();
         if(child!=data[i].state){
           $("#"+data[i].id).children().eq(1).html(data[i].state);
         }
       }
     })
     state=false;
   }
   else {
     return;
   }
 }

 function create(){
   /*
   $.get("/only_page/create_server",function(data){
     append='<tr id="'+data.id+'"><td>'+data.id+'</td><td>'+data.state+'</td><td>'+data.key_name+'</td><td><a data-remote="true" href="/only_page/stop_server?server_id='+data.id+'">Stop</a> <a data-remote="true" href="/only_page/start_server?server_id='+data.id+'">Start</a> <a href="/only_page/install_puppet?server_id='+data.id+'">Puppet-install</a></td></tr>'
     $('#main tr:nth-last-child(2) ').after(append);
   })*/
   append='<tr id="id"><td>id</td><td>state</td><td>key_name</td><td><a data-remote="true" href="/only_page/stop_server?server_id=">Stop</a> <a data-remote="true" href="/only_page/start_server?server_id=">Start</a> <a href="/only_page/install_puppet?server_id=">Puppet-install</a></td></tr>'
   $('#main tr:nth-last-child(3) ').after(append);
 }

 function openConsole(server_id){
   $('#main tr:last-child').show();
   $('textarea').attr('id',"ta_"+server_id);
 }

 function scriptsend(ref){
   if(ref.value.indexOf("puppet go")!=-1){
     id=ref.id.split('_')[1];
     what=ref.value.replace("puppet go","");
     $.post('/only_page/run_puppet_script?server_id='+id+'&what='+encodeURI(what),function(data){

     })
     ref.value="";
     alert("imaaa "+ref.id);
   }
   else if (ref.value.indexOf("puppet close")!=-1) {
     ref.value="";
     $('#main tr:last-child').hide();
   }
 }
</script>